name: GitHub Custom Action
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: custom-action:latest

      - name: Run custom action
        uses: ./ # Uses the Dockerfile in the root directory
        with:
          enterprise_slug: ${{ secrets.ENTERPRISE_SLUG }}
          auth_token: ${{ secrets.AUTH_TOKEN }}